name: "Tarball"
on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/tarball.yaml"
  workflow_dispatch:
env:
  PROTON_GE_RELEASE: "GE-Proton7-15"
  RELEASE: "1"
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Install required system packages using apt-fast"
        run: >-
          DEBIAN_FRONTEND=noninteractive apt-fast install --no-install-recommends -y autoconf patch
      - name: "Checkout Proton GE Custom"
        uses: "actions/checkout@v3"
        with:
          repository: "GloriousEggroll/proton-ge-custom"
          ref: "${{ env.PROTON_GE_RELEASE }}"
          submodules: "recursive"
          fetch-depth: 0
      - name: "Apply patches"
        run: "./patches/protonprep-valve-staging.sh"
      - name: "Store vdk3d-proton's build hash"
        run: "git describe --always --exclude=* --abbrev=15 --dirty=0 > BUILD"
        working-directory: "vkd3d-proton"
      - name: "Store vdk3d-proton's version"
        run: "git describe --always --tags --dirty=+ > VERSION"
        working-directory: "vkd3d-proton"
      - name: "Store dxvk-nvapi's version"
        run: "git submodule status -- dxvk-nvapi > dxvk-nvapi/VERSION"
      - name: "Store proton's date"
        run: "git show -s --format=%cs > DATE"
      - name: "Store proton's version"
        run: "git describe --tags > VERSION"
      - name: "Determine vulkan wine version"
        run: "echo \"VK_XML_VERSION=$(awk -v FS='VK_XML_VERSION = ' 'NF>1{print $2}' dlls/winevulkan/make_vulkan)\" >> $GITHUB_ENV"
        working-directory: "wine"
      - name: "Download vk.xml"
        run: "curl -LsSO https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/v${{ env.VK_XML_VERSION }}/xml/vk.xml"
        working-directory: "wine"
      - name: "Cleanup"
        run: "find . -xtype f -iname *.orig -delete"
      - name: "Create .tar.xz"
        run: "tar --exclude='.git' --exclude='.' --exclude='..' -cJvf proton-ge-custom-src.tar.xz * .*"
      - name: "Create SHA256SUMS file"
        run: "sha256sum -b proton-ge-custom-src.tar.xz > SHA256SUMS"
      - name: "Create release"
        uses: "softprops/action-gh-release@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.LCTRS_BOT_TOKEN }}"
        with:
          draft: false
          prerelease: false
          release_name: "${{ env.PROTON_GE_RELEASE }}-${{ env.RELEASE }}"
          tag_name: "${{ env.PROTON_GE_RELEASE }}-${{ env.RELEASE }}"
          files: |
            proton-ge-custom-src.tar.xz
            SHA256SUMS
